from time import sleep
print ("hey my name Yehudi.")
print ("i'm 22 years old and very very veeeery stupid.")
print ("no idea what that had to do with anything but doesn't mater.")
x = input ("by the way, who are you?.")
print ( x +"?, wierd name.")
print ("no offence but i think peter or George would fit you beter.")
print ("i mean " + x +" is cool but you deserve beter.")
d1a = input ("don't you think?")
if d1a == "yes":
     print ("thank god someone at least knows what is good for them")
elif d1a == "no":
     print ("my god, well if that is what you want i can't help ya")

print ("either way " + x + " if that is you real name")
print ("i need to ask you a few more questions for...... reshearch purpose..")
print ("like for instance...wait LOOK OUT!")
print ("*type a to dodge.*")
print ("*type b to stand still.*")
d2a = input ("what do you do?")
if  d2a == "a":
     print ("*as you dodge out of the way s huge explotion erupts at the spot where you were standing*")
     print ("my god that was close, nice dodge " + x + " didn't think you had it in ya")
     print ("looks like the city is under attack again")
     print ("follow me!")
     print ("*type a to follow*")
     print ("*type b to run away*")
     d3a = input ("what do you do?")
     if d3a == "b":
          print ("he..HEY WHERE ARE YOU GOING!")
          print ("*as you run away from yehudi you hear more explotions coming from all around you.*")
          print (x + ": i have to get out of here." )
          print ("*type a to flee the city*")
          print ("*type b to go to your familly*")
          d4a = input ("*what do you do?*")
          if d4a == "a":
               print ("*you start running as fast as you can towards the edge of the city*")
               print ("*on your way you see more people running away and getting blown up*")
               print ("*you notice that as you're running a gun shop that has been abandoned*")
               print (x + " : hmmmm could be handy.")
               print ("*type a to go into the gun shop*")
               print ("*type b to keep running*")
               d5a = input ("*what do you do?*")
               if d5a == "a":
                    print ("*without a speck of hesitation you rush over towards the store*")
                    print ("*you kick the door in and run towards the counter*")
                    print ("*you notice that most of the huns have already been taken*")
                    print ("*you start seaching the place as fast as possible but only find a few guns*")
                    print (x + " : shit just my luck. hmmm wich one should i take?")
                    print ("*type a to take the sniper and sun-glasses*")
                    print ("*type b to take the ak47 and sigar*")
                    print ("*type c to take everything*")
                    d6a = input ("what do you do?")
                    if d6a == "a":
                         print (x + " : no scope time")
                         print("*at that moment other people enter the store*")
                         print("*they are carying multiple guns and look at you angry*")
                         print("terrorist : well well well. if it isn't" + x )
                         print("terrorist : looks like it's our lucky day boys, LIGHT EM UP!")
                         print ("*type a to no-scope them")
                         print ("*type b to hard-scope them")
                         d7a = input ('what do you do?')
                         if d7a == "b":
                              print ("*you quickly pop up from behind the counter and try to aim as fast as possible*")
                              print ("*but not a second later your body get filled with bullets*")
                              print ("*you fall to the ground as your conciousnes fades away")
                              print ("GAME OVER")
                         elif d7a == "a":
                              print ("*you put on the sunglasses as you grab the sniper*")     
                              print ( x + " : get ready to get rekt noob")
                              print ("*as you hold the sniper with one arm, you shoot the first guy with out breaking a sweat*")
                              print ("*with your other hand you grab your phone and quickly start playing the song Bangarang from skrilex*")
                              print ('*meanwhile you jump up into the air spinning as you do and shoot the second guy')
                              print ("")
